### PR TITLE
Feature : Controller Support

### PR DESCRIPTION
**Pull request by sillyangel**
Im still working on this, don't pull yet

### CODE REVIEW

**Comment by colbychittenden** [comment]
this will be cool when its finished

**Comment by sillyangel** [comment]
using [minecraft bedrock](https://minecraft.wiki/w/Controls#Controller) controls

**Comment by colbychittenden** [comment]
nice

**Comment by FlamedDogo99** [comment]
Looking good so far. I have several ideas, and I'm happy to make any of them.
- [ ] Display a fake cursor when pointerlock is not called. 
- We already have functions that fire when entering and exiting pointerlock, so we can update the cursor's visibility from there.
- `window.fakelock` can determine if joystick movement is applied to in-game movement, or to the fake cursor in-menu
- To draw the cursor, we can just use a `position: absolute` element to display an image, similar to the on-screen buttons. (It would be fun to use the legacy edition pointer) cursor

- We'd just need to store x and y position global variables, from which we could dispatch hover, mouseover, and click events as needed.
-  [ ] Custom keyboard
-  I have no idea what the best way to do this is, but it's necessary for joining servers, naming items, and so on.

**Comment by FlamedDogo99** [comment]
Also you should update the keyboard section to the newest version.

**Comment by FlamedDogo99** [comment]
With much of Eagler Mobile being reworked, it will likely be difficult to resolve the branch conflicts in this pull request. Unless you indicate that you plan to update this branch, it will likely be closed in favor of recreating gamepad support with v3.0. You have until v3.1 to take any actions.

**Pull request closed without merging**
