### PR TITLE
add eaglermobile for eaglerforge

### PR DESCRIPTION
**Pull request by radmanplays**
this should work on every browser!

### CODE REVIEW

**Review by FlamedDogo99 — COMMENTED** [review]
Is this just renaming the file?

**Review by FlamedDogo99 — CHANGES_REQUESTED** [review]
Also, you should update this with the current branch as well

**Comment by radmanplays** [comment]
> Is this just renaming the file?

I made a new file called "eaglermobile-ef.js" and pasted in the userscript in it and since its javascript it works with eaglerforge(I've tested it on chrome)

**Comment by radmanplays** [comment]
> Also, you should update this with the current branch as well

done

**Pull request merged**
