### PR TITLE
Separate Mobile Controls From Other Features

### PR DESCRIPTION
**Pull request by RealPlurr**
Hopefully will work I probably messed up with } in wrong place if so fix it. Anyways it muss work technically, I'll test it in a while and inform about results here

### CODE REVIEW

**Comment by RealPlurr** [comment]
Yeah Messed up leme update

**Comment by RealPlurr** [comment]
Now its ready to go, I tested and it works fine.

**Comment by PlurrYT-Kolama** [comment]
kinda out of date beacuse of issue i wont close it beacuse ill update it to new version after issue with keyboard will get fixed

**Comment by FlamedDogo99** [comment]
Please provide some explanation for the change.

**Comment by RealPlurr** [comment]
Ok. So this just changes line where it checks for mobile. I just changed this line so it removes alerts and from if(! ismobile i deleted ! And now this if called if device is mobile. Then i opened { for rest of code so one like it was and second } moved go whole bottom. I understand still can be false positives on very very old devices or browsers but mainly it works on several browsers and devices (tested with my community)

**Comment by RealPlurr** [comment]
Aka mobile buttons will now appear only on mobile devices and wont appear on pc

**Comment by colbychittenden** [comment]
but why would you be using this userscript on pc anyway?

**Comment by PlurrYT-Kolama** [comment]
i mean if u do public launcher like uh it will probably need some detection

**Comment by colbychittenden** [comment]
I mean for my launcher https://webmc.xyz it just detects if your on mobile and redirects you to https://m.webmc.xyz so it kinda is useless

**Comment by FlamedDogo99** [comment]
Apologies for the late reply. With gamepad support in the works and keyboard events fixed for Android users, it's looking like this will be useful for more than mobile. As more functionality is added, I'm planning on allowing dynamic enabling and disabling of the different sections. This means that this check will likely be removed all-together soon. Thanks for taking the time to submit a pull request.

**Pull request closed without merging**
